# This workflow is a simple ci/cd pipeline that runs some tests and will deploy the
# project (TODO)

name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ci:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        pnpm-version: [8.x]

    steps:
    - uses: actions/checkout@v2
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install pnpm
      run: npm install -g pnpm@${{ matrix.pnpm-version }}

    - name: Install dependancies
      run: pnpm install --frozen-lockfile --shamefully-hoist

    - name: Run test
      run: pnpm test
      env:
        CI: true
